# Generated by Django 4.2.11 on 2024-04-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='max_range',
            field=models.IntegerField(default=100),
        ),
    ]
